region                    = "eu-west-1"				//Region where aws resources will be provided
subnet_public1_id  	  = "subnet-0e98b4b49d56f3ba3"		//Public subnet ID (the subnets will be attached to the lambda function for communitcation to other services like rds in vpc)
subnet_private_id 	  = "subnet-01da78d121e4af2b4"          //Private Subnet ID
subnet_public2_id         = "subnet-0192fcf75eb938a9a"          //Public Subnet ID
subnet_private2_id        = "subnet-0f7e9dcd3cc7c2a8b"		//Private subnet ID
subnet_private3_id        = "subnet-0ea3b3612f410970d"		//Private subnet ID
iam-role 		  = "wideui-lambda-tf-role"		//IAM role name which will be created 
lambda-function 	  = "wideui-backend-tf"			//Lambda-fucntion Nname
security_group_id	  = "sg-0ebffe53c03b1ca58"		//Security group ID (This is wideui-backend security group ID, currently we need these roles)
aws_s3_bucket             = "wideui-backend-tf"			//S3 bucket name
bucket_name                = "wideui-backend-tf"		//Description of the  bucket
zipname                   = "wideui-backend_lambda.zip"		//ZIP file name (this will be backend code, this will be deployed as zip to lambda fucntion from s3)
#domain_name               = "wideui-backend-tf.dev.wingd.digital" 	//Domain name that will be associated with the API gateway URL
#certificate_arn           = "arn:aws:acm:eu-west-1:901259681273:certificate/3f404b71-f1a1-4b8f-9c82-4dd062fc9e16"	//Certificate that will be used with the domain *.dev.wingd.digital
