region                    = "eu-west-1"				//Region where aws resources will be provided
subnet_private_id 	  = "subnet-0a01eaf265e0c4a22"          //Private Subnet ID
subnet_private2_id        = "subnet-017e6680aa553f00a"		//Private subnet ID
subnet_private3_id        = "subnet-05ac4e4e165423e65"		//Private subnet ID
iam-role 		  = "wideui-lambda-role"		//IAM role name which will be created 
lambda-function 	  = "wideui-backend-dev2"			//Lambda-fucntion Nname
security_group_id	  = "sg-0f5f61ebea049beea"		//Security group ID (This is wideui-backend security group ID, currently we need these roles)
aws_s3_bucket             = "wideui-dev2-backend"			//S3 bucket name
bucket_name                = "wideui-dev2-backend"		//Description of the  bucket
zipname                   = "wideui-backend_lambda.zip"		//ZIP file name (this will be backend code, this will be deployed as zip to lambda fucntion from s3)
domain_name               = "wideui-backend.dev2.wingd.digital" 	//Domain name that will be associated with the API gateway URL
certificate_arn           = "arn:aws:acm:eu-west-1:503263480993:certificate/b40966f6-3573-4ab7-b17b-b21506e0acca"	//Certificate that will be used with the domain *.dev.wingd.digital
