prefix                             = "wingd-dev2"
region                             = "eu-west-1"
engine_version                     = "5.7.38"
db_instance_class                  = "db.t2.medium"
db_allocated_storage               = "30"
db_username                        = "evt"
db_password                        = "SunLight#6"
db_port                            = "3306"
identifier                         = "rds-dev2-mysql-evt"
private_subnet_ids                 = ["subnet-0a01eaf265e0c4a22", "subnet-017e6680aa553f00a", "subnet-05ac4e4e165423e65"]          // Manual Update required
vpc_cidr_block                     = "10.0.0.0/16"
vpc_id                             = "vpc-007a716c0fe814284"      // Manual Update required
ingress_with_cidr_blocks_from_port = 3306
ingress_with_cidr_blocks_to_port   = 3306
protocol                           = "tcp"
egress_with_cidr_blocks_from_port  = 0
egress_with_cidr_blocks_to_port    = 0
sg_engress_cidr_block              = "0.0.0.0/0"
max_allocated_storage              = 60
ca_cert_identifier                 = "rds-ca-2019"

