prefix                              = "wingd-dev2"
region                              = "eu-west-1"
evt_instance_type                   = "t3.small"
sizop_instance_type                 = "t2.small"
wideonline1_instance_type           = "t3.medium"
wideonline2_instance_type           = "t3.medium"
private_subnet_id                   = "subnet-0a01eaf265e0c4a22"           // Manual Update required
vpc_id                              = "vpc-007a716c0fe814284"              // Manual Update required
vpc_cidr_range                      = "10.0.0.0/16"
iam_instance_profile                = "ssm-ec2-role"
volume_size                         = 30
public_subnets                      = ["subnet-0eafb64b69e0d31e8", "subnet-0efda700d87db111f"]      // Manual Update required
ingress_with_cidr_blocks_from_port1 = 80
ingress_with_cidr_blocks_to_port1   = 80
ingress_with_cidr_blocks_from_port2 = 443
ingress_with_cidr_blocks_to_port2   = 443
ingress_with_cidr_blocks_from_port3 = 22
ingress_with_cidr_blocks_to_port3   = 22
protocol                            = "tcp"
backend_protocol                    = "HTTP"
backend_port                        = 80
https_listeners_port                = 443
https_listeners_protocol            = "HTTPS"
sg_alb_ingress_rules                = ["http-80-tcp","https-443-tcp"]
certificate_arn                     = "arn:aws:acm:eu-west-1:503263480993:certificate/1721039f-aa62-414a-920d-59e0499735d0"      // Manual Update required
subnet_vpc_endpoint                 = ["subnet-0a01eaf265e0c4a22"]                           // Manual Update required
bucket_name_1                       = "wingd-elb-dev2-567y"				// Manual Update required
